apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: n8j23kxe0-python 
  janus-idp.io/tekton: n8j23kxe0-python
  backstage.io/kubernetes-id: n8j23kxe0-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: n8j23kxe0-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml