apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: n8j23kxe0-python-gitops
  description: This is GitOps manifest for n8j23kxe0-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=n8j23kxe0-python
    backstage.io/kubernetes-id: n8j23kxe0-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: n8j23kxe0-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:n8j23kxe0-python
